In [23]:
import pandas as pd
import numpy as np
import pymysql
import jieba
import jieba  
import jieba.posseg as pseg  
import os  
import sys  
from sklearn import feature_extraction  
from sklearn.feature_extraction.text import TfidfTransformer  
from sklearn.feature_extraction.text import CountVectorizer 

In [24]:
import pandas as pd
df = pd.read_csv(ready_to_read_file)
df2=df.drop_duplicates(subset=['positionId'])
df2.to_csv(ready_to_write_file)

NameError: name 'df' is not defined

In [208]:
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='6865215441',
                             db='LAGOU',
                             charset='utf8',
                             cursorclass=pymysql.cursors.DictCursor)
cursor = connection.cursor()

In [54]:
sql = 'SELECT detail FROM `detail` limit 50'

In [55]:
cursor.execute(sql)
detail_list = cursor.fetchall()

In [56]:
corpus_before = []
for detail in detail_list:
    corpus_before.append(detail['detail'])
print(corpus_before.__len__())

50


In [57]:
chrs = ['，','。','！','、','；','：','？','~','(',')','；',';',',','\n','\t','/','-','.','\'']
corpus = []
for line in corpus_before:
    for ch in chrs:
        line = line.replace(ch,'')
    Word_spilt_jieba = jieba.cut(line,cut_all = False)
    line = ' '.join(Word_spilt_jieba)
    corpus.append(line)

In [58]:
# corpus=["我 来到 北京 清华大学",#第一类文本切词后的结果，词之间以空格隔开  
#         "他 来到 了 网易 杭研 大厦",#第二类文本的切词结果  
#         "小明 硕士 毕业 与 中国 科学院",#第三类文本的切词结果  
#         "我 爱 北京 天安门"]
vectorizer=CountVectorizer()    #该类会将文本中的词语转换为词频矩阵，矩阵元素a[i][j] 表示j词在i类文本下的词频  
transformer=TfidfTransformer()  #该类会统计每个词语的tf-idf权值  
X = vectorizer.fit_transform(corpus)

In [50]:
# 稀疏矩阵降维  可以使用HashingVectorizer()减少维度
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(100)
X_transformed = svd.fit_transform(X)
X_transformed

In [72]:
tfidf=transformer.fit_transform(X)#第一个fit_transform是计算tf-idf，第二个fit_transform是将文本转为词频矩阵  
word=vectorizer.get_feature_names()#获取词袋模型中的所有词语  
weight=tfidf.toarray()#将tf-idf矩阵抽取出来，元素a[i][j]表示j词在i类文本中的tf-idf权重  

In [21]:
# for i in range(len(weight)):#打印每类文本的tf-idf词语权重，第一个for遍历所有文本，第二个for便利某一类文本下的词语权重  
#     print(u"-------这里输出第",i,u"类文本的词语tf-idf权重------")  
#     for j in range(len(word)):  
#         print('{} {} '.format(word[j],weight[i][j]))

-------这里输出第 0 类文本的词语tf-idf权重------
12 0.08640755677347638 
13 0.0 
18 0.0 
20 0.0 
2010 0.0 
2016 0.0 
about 0.0 
adidasnike 0.0 
airdroid 0.0 
airdroidworking 0.0 
always 0.0 
and 0.0 
api 0.0 
app 0.0 
are 0.0 
around 0.0 
axurevisoomnigraffle 0.08640755677347638 
big 0.0 
by 0.0 
challenging 0.0 
chance 0.0 
commitment 0.0 
django 0.0 
excellencewe 0.0 
exciting 0.0 
for 0.0 
get 0.0 
growing 0.0 
h5 0.0 
hackers 0.0 
here 0.0 
hire 0.0 
holy 0.0 
html5 0.0 
http 0.0 
in 0.0 
ios 0.0 
iosandroid 0.0 
iosmac 0.0 
is 0.0 
job 0.0 
life 0.0 
linux 0.0 
linuxfreebsd 0.0 
lnmplamp 0.0 
make 0.0 
means 0.0 
memcache 0.0 
million 0.0 
mysql 0.0 
mysqlnosql 0.0 
mysqlredismongodb 0.0 
nginx 0.0 
not 0.0 
objectivec 0.0 
offering 0.0 
oms 0.0 
on 0.0 
only 0.0 
over 0.0 
people 0.0 
photoshopillustratoraxure 0.0 
php 0.0 
pioneers 0.0 
problems 0.0 
product 0.0 
provide 0.0 
providing 0.0 
ps 0.0 
python 0.0 
pythonnodejsperlbash 0.0 
qq 0.0 
really 0.0 
redis 0.0 
rewarding 0.0 
shellpytho

待遇 0.0 
微信 0.0 
必须 0.0 
快速 0.0 
忽略 0.0 
思想 0.0 
性格开朗 0.0 
性能 0.0 
情人节 0.0 
情况 0.0 
意思 0.0 
意识 0.09231324942106514 
成为 0.0 
成功 0.0 
成本 0.0 
成果 0.0 
成立 0.0 
我们 0.0 
手机 0.0 
手机用户 0.0 
手绘 0.0 
扎实 0.0 
执着 0.0 
技巧 0.07847469574438926 
技术 0.14866907413862793 
投入 0.0 
报名 0.0 
招商局 0.0 
招聘 0.0 
择优录取 0.0 
择优录用 0.0 
持续 0.0 
指导 0.0 
按时 0.0 
掌握 0.0 
排版 0.0 
探索 0.0 
接口 0.2769397482631954 
推进 0.0 
描述 0.0 
提供 0.0 
提升 0.0 
插画 0.0 
搜索引擎 0.0 
搭建 0.0 
操作 0.0 
操作技能 0.0 
改为 0.0 
改版 0.0 
攻坚 0.0 
攻城 0.0 
故障 0.0 
数万家 0.0 
数据 0.07847469574438926 
数据库 0.06865608565481454 
数据格式 0.0 
数据结构 0.0 
数百万 0.0 
整个 0.0 
整体 0.0 
文档 0.0 
方案 0.0 
方法 0.0 
方面 0.0 
日常 0.0 
时间 0.0 
最大 0.0 
最好 0.0 
有点 0.0 
服务 0.0 
服务器 0.09231324942106514 
期待 0.0 
未来 0.0 
本科 0.0 
机会 0.0 
机制 0.0 
条为 0.0 
条件 0.0 
极客 0.09231324942106514 
架构 0.07847469574438926 
架构设计 0.0 
查询 0.06865608565481454 
树立 0.0 
根据 0.061040179993107145 
框架 0.13731217130962908 
案例 0.0 
桌游 0.0 
梦想 0.0 
梳理 0.0 
模块 0.0 
欢迎 0.0 
正在 0.0 
正式 0.0 
毅力 0.0 
比较 0.0 
氛围 0.0 
水平 0.0 
沉淀 0.0 


In [93]:
word

['10',
 '100',
 '102',
 '11',
 '12',
 '13',
 '18',
 '18002400',
 '20',
 '2010',
 '2016',
 '22',
 '23',
 '24',
 '35',
 '48',
 '60',
 '88',
 '9001830',
 'about',
 'acm',
 'adidasnike',
 'adonet',
 'agile',
 'airdroid',
 'airdroidworking',
 'ajax',
 'always',
 'and',
 'android',
 'androidios',
 'api',
 'app',
 'app3',
 'ar',
 'are',
 'around',
 'aspnetaspnet',
 'aws',
 'axurevisoomnigraffle',
 'basic',
 'big',
 'brionasgithubio',
 'bug',
 'by',
 'b座',
 'cbd',
 'cdn',
 'challenging',
 'chance',
 'ciyii',
 'cocoauikit',
 'commitment',
 'coreanimation',
 'cs',
 'css',
 'css3',
 'dba',
 'delphi',
 'delphivisual',
 'demo',
 'development',
 'devops',
 'div',
 'django',
 'djangoflaskwebpypylons',
 'dll',
 'dnshttphttpsquic',
 'dom',
 'entityframeworklinqenterprise',
 'erp',
 'es',
 'es20',
 'excellencewe',
 'excelword',
 'exciting',
 'fluxangularjs',
 'for',
 'framework',
 'gc',
 'get',
 'git',
 'github',
 'growing',
 'h5',
 'hackers',
 'hamllesscoffeescriptreact',
 'happy',
 'here',
 'heroku',


In [90]:
for i in range(10):
    for j in range(100):
        print(weight[i][j],end=' ')
    print()

0.0 0.0 0.0 0.0 0.0973022570715 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.116324733531 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.126316514926 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0891440617288 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit_transform(corpus)

<50x1576 sparse matrix of type '<class 'numpy.float64'>'
	with 4118 stored elements in Compressed Sparse Row format>

In [158]:
position_name = ['产品经理','前端开发工程师','测试工程师','平面设计师','UI设计师']
sql_list = []
detail_list = []
corpus_raw = []
for name in position_name:
    sql_list.append("SELECT detail.detail FROM `L拉勾`, `detail`\
    WHERE L拉勾.职位ID=detail.id AND L拉勾.职位名称='%s' limit 5"%(name))
for sql in sql_list:
    cursor.execute(sql)
    detail_list = cursor.fetchall()
    for detail in detail_list:
        corpus_raw.append(detail['detail'])
#     break
print(corpus_raw.__len__())

25


In [184]:
chrs = ['，','。','！','、','；','：','？','~','(',')','；',';',',','\n','\t','/','-','.','\'']
corpus = []
for line in corpus_raw:
    for ch in chrs:
        line = line.replace(ch,'')
    Word_spilt_jieba = jieba.cut(line,cut_all = False)
    line = ' '.join(Word_spilt_jieba)
    corpus.append(line)
print(corpus[0])

职位 要求 1 有 互联网 和 移动 互联网 行业 3 年 以上 产品 经理 从业 经验 2 独立 承担 项目 丰富 的 ERP 产品设计 经验 2 懂 app 基本 设计 流程 熟悉 微信 公众 号 的 后台 框架 及 运营 3 具备 项目 方案 起草 需求 整理 开发计划 及 相关 业务 对接 的 能力 4 有 很 强 的 产品 逻辑 与 项目 执行 能力 协调 沟通 部门 内外部 的 资源 5 具备 决策 和 项目 团队 管理 经验


In [160]:
vectorizer=CountVectorizer()    #该类会将文本中的词语转换为词频矩阵，矩阵元素a[i][j] 表示j词在i类文本下的词频  
X = vectorizer.fit_transform(corpus)

transformer=TfidfTransformer()  #该类会统计每个词语的tf-idf权值  
tfidf=transformer.fit_transform(X)

In [201]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [161]:
word=vectorizer.get_feature_names()#获取词袋模型中的所有词语  
weight=tfidf.toarray()#将tf-idf矩阵抽取出来，元素a[i][j]表示j词在i类文本中的tf-idf权重 

In [204]:
for i in range(20):
    for j in range(20):
        print(weight[i][j],end=' ')
    print()

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.116133204036 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0924905834836 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0801139896408 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.230164048616 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0930653754409 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.106744931403 0.106744931403 
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 0.0922569

In [162]:
print('weight',weight.shape)
print('word',word.__len__())

weight (25, 925)
word 925


In [178]:
arr = []
for i in range(1,6):
    for j in range(1,6):
        arr.append(i)
y = np.array(arr)
y

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5,
       5, 5])

In [179]:
from sklearn import svm 
clf = svm.SVC()
clf.fit(weight,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [209]:
sql = "SELECT detail.detail FROM `L拉勾`, `detail`\
    WHERE L拉勾.职位ID=detail.id AND L拉勾.职位名称='产品经理' limit 20"
cursor.execute(sql)
detail_list = cursor.fetchall()
test_raw = []
for detail in detail_list:
    test_raw.append(detail['detail'])
chrs = ['，','。','！','、','；','：','？','~','(',')','；',';',',','\n','\t','/','-','.','\'']
test_corpus = []
for line in test_raw:
    for ch in chrs:
        line = line.replace(ch,'')
    Word_spilt_jieba = jieba.cut(line,cut_all = False)
    line = ' '.join(Word_spilt_jieba)
    test_corpus.append(line)
print(test_corpus.__len__())

# vectorizer=CountVectorizer()    #该类会将文本中的词语转换为词频矩阵，矩阵元素a[i][j] 表示j词在i类文本下的词频  
X = vectorizer.transform(test_corpus)

# transformer=TfidfTransformer()  #该类会统计每个词语的tf-idf权值  
tfidf=transformer.transform(X)

20


In [210]:
test_data = tfidf.toarray()

In [211]:
clf.predict(test_data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])